### ISSUE TITLE
Emoji modifiers not removed by emoji-strip

### ISSUE THREAD

**Issue by ifross89** [khalifenizar/emoji-strip#3]
For example, the following string contains emoji modifiers (http://emojipedia.org/skin-tone-modifiers/):

`Just casually bumped into @andyroddick in the commentary box @bbctennis @Wimbledon 👍🏻👍🏻`

emoji-strip currently does not remove these from strings.

**Comment by EyePulp** [comment]
+1 - I'll see if I can figure out a patch for this, but I'm pretty emoji-ignorant. =)

**Comment by khalifenizar** [comment]
Fixed this in version 1.0.0. Already published to npm.
