### ISSUE TITLE
Updated gemoji dependency to 1.0.0

### ISSUE THREAD

**Issue by Kikobeats** [khalifenizar/emoji-strip#4]
stable version was released. What about to update it? :-)

**Comment by khalifenizar** [comment]
The `emoji-strip` module will not use `gemoji` anymore for the foreseeable future. Instead it's using a different module behind the scenes ([emoji-regex](https://www.npmjs.com/package/emoji-regex)).

Shouldn't need to update the dependency anymore. Thanks for reporting!
